version: '3.4'

services:
  order.api:
    user: root
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5000:8080"
    volumes:
     - order-pictures:/app/wwwroot/pictures  
  stock.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5010:8080"
  payment.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5020:8080"
  sqlserver:
    user: root
    environment:
      SA_PASSWORD: "Password12*"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql/data
      